### ISSUE TITLE
Code snippets are only shown on the first half of the screen

### ISSUE THREAD

**Issue by adelriosantiago** [boydoglabs/boydog-demo#4]
Code snippets need to take full width on mobile view.

![image](https://user-images.githubusercontent.com/5462382/95504889-071a8680-0973-11eb-910d-87dfb14a7186.png)

**Comment by M4yankChoudhary** [comment]
Can i take this ?

**Comment by ShalomSagi** [comment]
Can I take this one? 😄

**Comment by evandroLutz** [comment]
yesterday i have send an pr to this issue, please valid and merge, thank you.

**Comment by adelriosantiago** [comment]
Closed in https://github.com/boydoglabs/boydog-demo/pull/7
