### ISSUE TITLE
Wash out not needed steps in instructions

### ISSUE THREAD

**Issue by adelriosantiago** [boydoglabs/boydog-demo#8]
Currently instructions look like this:

![image](https://user-images.githubusercontent.com/5462382/95619820-d4d15d80-0a34-11eb-91d1-1e33900e391a.png)

Important lines are bold, while non important lines are normal text.

Change this so that important lines are normal text while non important lines are grayed out or washed otu (i.e. they are less visible)

**Comment by evandroLutz** [comment]
please assign to me

**Comment by adelriosantiago** [comment]
Done

**Comment by adelriosantiago** [comment]
Closed in https://github.com/boydoglabs/boydog-demo/pull/9
